"""add_guide_content

Revision ID: 0c1eed3ae048
Revises: a8229ba2bf1a
Create Date: 2026-03-04 16:31:36.429039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c1eed3ae048'
down_revision: Union[str, None] = 'a8229ba2bf1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guides', sa.Column('content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guides', 'content')
    # ### end Alembic commands ###
