"""add_reviews_table

Revision ID: 31c3e6a46a30
Revises: 0c1eed3ae048
Create Date: 2026-03-12 13:02:20.545733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31c3e6a46a30'
down_revision: Union[str, None] = '0c1eed3ae048'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
