"""doctor_settings_and_guide_cover

Revision ID: 3837cf473fb2
Revises: d1bde3751234
Create Date: 2026-03-03 13:11:46.689771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3837cf473fb2'
down_revision: Union[str, None] = 'd1bde3751234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_profiles', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('doctor_profiles', sa.Column('work_days', sa.String(), nullable=False))
    op.add_column('guides', sa.Column('cover_image_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guides', 'cover_image_id')
    op.drop_column('doctor_profiles', 'work_days')
    op.drop_column('doctor_profiles', 'is_active')
    # ### end Alembic commands ###
