"""appointment files and protocol

Revision ID: 864ea017c290
Revises: db44df3270f5
Create Date: 2026-03-03 18:59:53.740999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '864ea017c290'
down_revision: Union[str, None] = 'db44df3270f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('mongo_file_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_files_id'), 'appointment_files', ['id'], unique=False)
    op.add_column('appointments', sa.Column('protocol_file_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'protocol_file_id')
    op.drop_index(op.f('ix_appointment_files_id'), table_name='appointment_files')
    op.drop_table('appointment_files')
    # ### end Alembic commands ###
