"""split pet info

Revision ID: a8229ba2bf1a
Revises: 864ea017c290
Create Date: 2026-03-04 13:36:46.670785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8229ba2bf1a'
down_revision: Union[str, None] = '864ea017c290'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('pet_name', sa.String(), nullable=True))
    op.add_column('appointments', sa.Column('pet_details', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'pet_details')
    op.drop_column('appointments', 'pet_name')
    # ### end Alembic commands ###
