"""multi_doctor_and_balance

Revision ID: d1bde3751234
Revises: 587750b54ca1
Create Date: 2026-03-01 18:46:37.967957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1bde3751234'
down_revision: Union[str, None] = '587750b54ca1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('yandex_email', sa.String(), nullable=True),
    sa.Column('yandex_password', sa.String(), nullable=True),
    sa.Column('telemost_link', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_doctor_profiles_id'), 'doctor_profiles', ['id'], unique=False)
    op.add_column('appointments', sa.Column('doctor_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'appointments', 'users', ['doctor_id'], ['id'])
    op.add_column('guides', sa.Column('author_id', sa.Integer(), nullable=True))
    op.add_column('guides', sa.Column('free_snippet', sa.Text(), nullable=True))
    op.alter_column('guides', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_foreign_key(None, 'guides', 'users', ['author_id'], ['id'])
    op.add_column('users', sa.Column('unused_consultations', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'unused_consultations')
    op.drop_constraint(None, 'guides', type_='foreignkey')
    op.alter_column('guides', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('guides', 'free_snippet')
    op.drop_column('guides', 'author_id')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'doctor_id')
    op.drop_index(op.f('ix_doctor_profiles_id'), table_name='doctor_profiles')
    op.drop_table('doctor_profiles')
    # ### end Alembic commands ###
