"""add filenames to guide

Revision ID: db44df3270f5
Revises: 3837cf473fb2
Create Date: 2026-03-03 15:45:04.430040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db44df3270f5'
down_revision: Union[str, None] = '3837cf473fb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guides', sa.Column('pdf_filename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guides', 'pdf_filename')
    # ### end Alembic commands ###
